import { ReactQueryProvider } from "@/providers/reactquery-provider"
import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const virgil = localFont({
  src: "../fonts/Virgil.woff2",
})
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ReactQueryProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>{children}</body>
    </html>
    </ReactQueryProvider>
  )
}
