import { ReactQueryProvider } from "@/providers/reactquery-provider"
import "@/styles/globals.css"
import { type Metadata } from "next"
import localFont from "next/font/local"
import Header from "./_components/header"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const virgil = localFont({
  src: "../fonts/Virgil.woff2",
})
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ReactQueryProvider>
      <html lang="en" className={`${virgil.className}`}>
        <body className="bg-[url('/images/background.jpg')] bg-cover">
          <div className="mx-auto flex min-h-screen w-full max-w-6xl flex-col">
            <Header />
            {children}
          </div>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
