import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const virgil = localFont({
  src: "../fonts/Virgil.woff2",
})
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${virgil.className}`}>
      <body className="bg-[url('/images/background.jpg')] bg-cover">
        {children}
      </body>
    </html>
  )
}
